name: water_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
    
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  go_router: ^15.2.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.3
  import_sorter: ^4.6.0

# dart run import_sorter:main
import_sorter:
  comments: true
  exports:
    - lib/

flutter:
  uses-material-design: true
  generate: true

  assets:
  - assets/icons/